### PR TITLE
exit code of `stp validate` is always 0 

### PR DESCRIPTION
**Pull request by perlpunk**
I think stp should exit with code != 0 if validation fails. And output should possibly go to stderr.

### CODE REVIEW

**Comment by ingydotnet** [comment]
Good idea but really you don't use the count. Maybe change to something like this:

```
got_errors = false

  got_errors = true

process.exit Number got_errors
```

**Comment by perlpunk** [comment]
I thought the count could be useful someday, but yeah, until it's not used... updated

**Comment by perlpunk** [comment]
not really sure about error output though

**Comment by ingydotnet** [comment]
Applied. Pushed. Thanks!

**Comment by perlpunk** [comment]
my first coffeescript code \o/

**Pull request merged**
